### ISSUE TITLE
Text in message bubbles is not centered

### ISSUE THREAD

**Issue by yspreen** [MessageKit/MessageKit#1385]
**Describe the bug**
The right side of the bubble on sent messages has more spacing than the left. Same issue, but flipped, for received messages.

**To Reproduce**
Steps/code to reproduce the behavior:

I reproduced it in the basic VC of the example app [here](/yspreen/MessageKit-off-center).
```swift
    func messageStyle(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> MessageStyle {
        return .bubble
    }
```

**Expected behavior**
The spacing should be equal.

**Screenshots**
https://imgur.com/a/Y5Y5Rfk

**Environment**
- What version of MessageKit are you using?
  - master branch
- What version of iOS are you running on?
  - 13.5
- What version of Swift are you running on?
  - 5
- What device(s) are you testing on? Are these simulators?
  - iPhone 11 Pro, yes
- Is the issue you're experiencing reproducible in the example app?
  - yes, see above

**Additional context**
&mdash;

**Comment by yspreen** [comment]
See #990

**Comment by yspreen** [comment]
This (stupid) workaround fixes it:
```swift
      cell.messageLabel.textInsets.left = 16
      cell.messageLabel.textInsets.right = -16
```

**Comment by yspreen** [comment]
Can I get this confirmed as a bug before it goes stale? 😄

**Comment by yspreen** [comment]
I'm not sure why this wasn't approved as a bug. I mean I can add the fix that worked for me personally and create a PR?

**Comment by yspreen** [comment]
This issue has been bugging me for years to be honest. With the alignment inconsistencies of bubble tails, the regular bubble message is still one of the best options. So what do you think @nathantannar4? Mentioning as you've been commenting on the first issue at #990

**Comment by kinoroy** [comment]
@yspreen Sorry this wasn't ever marked as confirmed. I'll reopen it now.

**Comment by kinoroy** [comment]
Hey @yspreen , so you can fix this without messing with the cell directly by changing the `incomingMessageLabelInsets`, and `outgoingMessageLabelInsets` on the `textMessageSizeCalculator` of your MessagesVC's `messagesCollectionViewLayout` object. The default insets are asymmetrical, I guess to account for the bubble tail style. These are the default insets:

```swift
    public var incomingMessageLabelInsets = UIEdgeInsets(top: 7, left: 18, bottom: 7, right: 14)
    public var outgoingMessageLabelInsets = UIEdgeInsets(top: 7, left: 14, bottom: 7, right: 18)
```

and you could change both the left and right to be 14, if you're using the bubble style.

I guess the `TextMessageSizeCalculator` should somehow take into account the bubble style when determining the default inset to use, but also maintain the ability for the user to set the insets themselves.

**Comment by yspreen** [comment]
Thanks @kinoroy.  
I'm just surprised that the default style is asymmetrical. Even the MK examples use the bubble style without a tail, exposing this exact bug...

Maybe taking the style into account makes sense. But then again, most people will probably not use the default bubble style anyway since the corner radius is dependent on the width of the message, making it inconsistent across messages.

**Comment by Kaspik** [comment]
Is this still an issue for 4.0.0 beta 1?

**Comment by Kaspik** [comment]
I'm hoping this was fixed in 4.0.0, let me know if not.

**Comment by monstermac77** [comment]
> This issue has been bugging me for years to be honest. With the alignment inconsistencies of bubble tails, the regular bubble message is still one of the best options. So what do you think @nathantannar4? Mentioning as you've been commenting on the first issue at #990

We're using 4.1.1 (the latest) and this is still an issue by default when using tailed messages. For the tailed message, you can see that the right hand side has more padding than the left. And for all of the messages above which have tails suppressed (since they're sent by the same user) there is more left padding on the message than the tailed message at the bottom, making for some very irregular looking messages.

<img width="175" alt="image" src="https://user-images.githubusercontent.com/3255298/225398132-117f6005-2a7e-4329-bd97-10e46503fe10.png">

**Comment by monstermac77** [comment]
All right, so after going through a lot of the issues posted here and playing around, I believe I have a decent solution to this very common problem. It involves making a custom cell, but most of you who are looking for this level of customization were probably going to end up creating it anyway. 

Creating a custom cell is pretty well documented, especially @wildseansy in comments like [this](https://github.com/MessageKit/MessageKit/issues/686#issuecomment-389677565). Once you've done that, you'll have the key function: `configure(with message: MessageType, at indexPath: IndexPath, and messagesCollectionView: MessagesCollectionView)` on your custom cell. This allows it to make its own layout decisions given a message and an index path. Note that both the frame of the "message" (the bubble) and the insets of the string inside the bubble (the label) need to be adjusted. If you only adjust the frame of the bubble, the text will have too much padding on one side. That's all you really need. Here's what I put in there to get it done: 

```
// this was one of the harder things to get work. Basically there's a message alignment problem when you only have
// the bubble tails on the last message the user sent in a row. The bubble aligns with the start of the tail
// rather than the start of the bubble of that message, so there's a bunch of left padding. So we move the bubble
// of those messages by 5 pixes so that they align with the bubble of the tail bubble, and then we also reduce the inset
// of the bubble on that side by about 5. That way you get text alignment and you get bubble alignment. Looks much better
// and matches what iMessage does.
if let source = messagesCollectionView.messagesCollectionViewFlowLayout.messagesDataSource as? ChatViewController{
    if source.sameSenderAsNext(at: indexPath){
        
        // move the bubble over by 5 by doing a dx shift, and then also to compensate for this telling the frame that it's 5 pixels more narrow (not sure if this is needed
        let totalShift = CGFloat(5)
        if !source.sentByMe(message: message){
            messageContainerView.frame = messageContainerView.frame.offsetBy(dx: totalShift, dy: 0)
            messageContainerView.frame = CGRect(x: messageContainerView.frame.minX, y: messageContainerView.frame.minY, width: messageContainerView.frame.width - totalShift, height: messageContainerView.frame.height)
        }else{
            messageContainerView.frame = messageContainerView.frame.offsetBy(dx: -totalShift, dy: 0)
            messageContainerView.frame = CGRect(x: messageContainerView.frame.minX, y: messageContainerView.frame.minY, width: messageContainerView.frame.width - totalShift, height: messageContainerView.frame.height)
        }
        
        // adjust the insets of the text for these types of messages specifically (ones that are by the same sender in a row), because they should be closer to what MessageKit considers the left-most side of the bubble (they consider the tail to be part of the bubble, but that doesn't really make sense when it comes to the text; this is the problem).
        if let layout = messagesCollectionView.messagesCollectionViewFlowLayout as? BubbleFlowLayout{
            if !source.sentByMe(message: message){
                var modifiedInset = layout.bubbleSizeCalculator.incomingMessageLabelInsets
                modifiedInset.left = modifiedInset.left - totalShift
                messageLabel.textInsets = modifiedInset
            }else{
                var modifiedInset = layout.bubbleSizeCalculator.outgoingMessageLabelInsets
                modifiedInset.right = modifiedInset.right - totalShift
                messageLabel.textInsets = modifiedInset
            }
        }
    }
}
```

After just a quick search it looks like this is in at least 4 issues here (#1368, #1156, #990, and here), so in case others from search engines land on any of those, I'll put a note directing them here. 
![Simulator Screen Shot - iPhone 14 Pro - 2023-03-22 at 18 45 31](https://user-images.githubusercontent.com/3255298/227055535-87e48570-dbd4-4b49-bac1-fa9476fa3b7b.png)
