### ISSUE TITLE
Bottom inset issue when (2nd) expected Keyboard Notification is not sent.

### ISSUE THREAD

**Issue by austinwright** [MessageKit/MessageKit#993]
This is an odd issue / edge case related to https://github.com/MessageKit/MessageKit/pull/787:

Overview:

When stepping through the `MessagesViewController+Keyboard.handleKeyboardDidChangeState(_:)` function with a hardware keyboard attached, you can usually see two notifications trigger the function in succession, one of which is discarded by the changes in the above PR. Following these steps to reproduce, you will see that only the discarded notification is sent, thus leaving the bottom content inset unchanged causing an overlap:

Steps:

0. Pre-req - Make changes to the example app (see code snippets below). Modify the AdvancedExampleViewController class as follows:
0.1 Disable the mock socket.
0.2 Add a UIAlertController actionSheet to one of the buttons
0.3 Launch the chat example in the simulator with the hardware keyboard connected and the software keyboard toggled off. (edited) 
1. Go to the 'advanced' view.
2. Type a multi-line attributed text (without going over the limit or deleting a line) and hit 'send'
3. Tap the button to present the actionSheet
4. Dismiss/cancel the actionSheet
Actual Result: Only one keyboard frame change notification is sent, and it happens to be the one ignored by the `guard !keyboardStartFrameInScreenCoords.isEmpty else {` condition in `MessagesViewController.handleKeyboardDidChangeState(_:)`. This means that the insets stay at 0. The effect in the UI is that the scrollview content is obfuscated by the inputAccessoryView.
Expected Result: Insets are re-calculated correctly.

Screenshots:

Scrolled up & held to show content:
![screen shot 2019-02-06 at 2 53 02 pm](https://user-images.githubusercontent.com/1952159/53183677-c1f0e780-35c9-11e9-867e-f01b4b94b28d.png)

The resting bottom content offset position after ending touches on the scrollview:
![screen shot 2019-02-06 at 2 52 11 pm](https://user-images.githubusercontent.com/1952159/53183748-e947b480-35c9-11e9-9260-7ad9dc44970f.png)

Some debugging screenshots if you want to dig through the values displayed:

![screen shot 2019-02-04 at 5 11 27 pm](https://user-images.githubusercontent.com/1952159/53184108-77239f80-35ca-11e9-9000-0e6fdb7ac2d6.png)
![screen shot 2019-02-04 at 5 10 41 pm](https://user-images.githubusercontent.com/1952159/53184109-77239f80-35ca-11e9-9f61-caf33fa68099.png)
![screen shot 2019-02-04 at 5 08 11 pm](https://user-images.githubusercontent.com/1952159/53184110-77239f80-35ca-11e9-87cb-c86e1b8c37d1.png)

Answers to boilerplate questions:

- What version of MessageKit are you using?
2.0

- What version of iOS are you running on?
iOS 11 - 12.1

- What version of Swift are you running on?
4.2

- What device(s) are you testing on? Are these simulators?
Happens on regular & 'X' Devices, and Simulators

- Is the issue you're experiencing reproducable in the example app?
Yes:
In `AdvancedExampleViewController`, comment out line 56:
```swift
                //self?.insertMessage(message)
```
and replace lines 208-209 with:
```swift
            }.onTouchUpInside {
                //print("Item Tapped")
                let actionSheet = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
                let action = UIAlertAction(title: "Cancel", style: .cancel, handler: nil)
                actionSheet.addAction(action)
                if let popoverPresentationController = actionSheet.popoverPresentationController {
                    popoverPresentationController.sourceView = $0
                    popoverPresentationController.sourceRect = $0.frame
                }
                self.navigationController?.present(actionSheet, animated: true, completion: nil)
```

**Comment by nathantannar4** [comment]
Got time to look at this tonight and indeed this is a problem. I pushed a hot fix to the 3.0.0 beta branch requiring that the device idiam also be .pad since I believe this was just an iPad bug

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ckakei** [comment]
#1001 issue still not fix 

The Problem is after present a ViewController on MessagesViewController, it will trigger  `UIResponder.keyboardWillChangeFrameNotification` and call `handleKeyboardDidChangeState `  
 It will make `messageCollectionViewBottomInset` become 0

After dismiss the ViewController and back to MessagesViewController, even we call `viewDidLayoutSubviews` it will not add back the correct bottom inset like `messageCollectionViewBottomInset = requiredInitialScrollViewBottomInset()`

Currently, i edit the MessageViewController.swift force isFirstLayout to be true  
```
    open override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        isMessagesControllerBeingDismissed = false
        isFirstLayout = true
    }
```
And call viewDidLayoutSubviews() in ChatViewController to hot-fix it

```
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        self.viewDidLayoutSubviews()
        MockSocket.shared.connect(with: [SampleData.shared.steven, SampleData.shared.wu])
            .onNewMessage { [weak self] message in
                self?.insertMessage(message)
        }
    }
```

**Comment by TobiasRe** [comment]
Same here. For me this bug results in a layout jump when navigating back to MessagesViewController, cutting off the last message.
Thanks @ckakei  your fix helps, but requires to change MessageKit itself.

**Comment by nathantannar4** [comment]
Would welcome a PR 😊

**Comment by whoyawn** [comment]
@austinwright I'm experiencing the same problem, but the offset gets messed up as well as the current scroll position. Are you able to scroll back normally after it gets out of view?

**Comment by nathantannar4** [comment]
@whoyawn have you looked at preventing `handleKeyboardDidChangeState` from being called? @ckakei indicated that it's called incorrectly when another view controller is presented, so make we could `gaurd` and return if the `MessagesViewController` is presenting another controller?

While forcing a layout in `viewDidAppear` I feel that solution is only a "Band-Aid" and doesn't fix the root issue.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by whoyawn** [comment]
Tried in my own project, and `handleKeyboardDidChangeState` seems to not have an effect on whether it's called or not. Actually, this is what did it for me:

```
...
        currentOffset = messagesCollectionView.contentOffset
        present(newImageVC, animated: true, completion: nil)
    }

    @objc func didTapFullScreenImage(_: UITapGestureRecognizer) {
        dismiss(animated: true, completion: nil)
        messagesCollectionView.contentOffset = currentOffset!
        currentOffset = nil
    }
```

Seems like putting frame adjusting code in MessagesViewController is hacky, but thoughts?

**Comment by dombryan94** [comment]
Using version 3.0.0 I still seem to have this issue, is there any other thoughts?

**Comment by Kaspik** [comment]
@whoyawn Any update on this? Are you able to create a PR for that to `development` branch?

**Comment by whoyawn** [comment]
Not yet

> Tried in my own project, and `handleKeyboardDidChangeState` seems to not have an effect on whether it's called or not. Actually, this is what did it for me:
> 
> ```
> ...
>         currentOffset = messagesCollectionView.contentOffset
>         present(newImageVC, animated: true, completion: nil)
>     }
> 
>     @objc func didTapFullScreenImage(_: UITapGestureRecognizer) {
>         dismiss(animated: true, completion: nil)
>         messagesCollectionView.contentOffset = currentOffset!
>         currentOffset = nil
>     }
> ```
> 
> Seems like putting frame adjusting code in MessagesViewController is hacky, but thoughts?

If this adjustment is fine I can put a PR, but I haven't heard back

**Comment by Kaspik** [comment]
If you can create a PR with that, we can check and test that definitely. :)

**Comment by whoyawn** [comment]
Is this the same issue as #1529? In my own code

> Not yet
> 
> > Tried in my own project, and `handleKeyboardDidChangeState` seems to not have an effect on whether it's called or not. Actually, this is what did it for me:
> > ```
> > ...
> >         currentOffset = messagesCollectionView.contentOffset
> >         present(newImageVC, animated: true, completion: nil)
> >     }
> > 
> >     @objc func didTapFullScreenImage(_: UITapGestureRecognizer) {
> >         dismiss(animated: true, completion: nil)
> >         messagesCollectionView.contentOffset = currentOffset!
> >         currentOffset = nil
> >     }
> > ```
> > 
> > 
> > Seems like putting frame adjusting code in MessagesViewController is hacky, but thoughts?
> 
> If this adjustment is fine I can put a PR, but I haven't heard back

I'm actually finding crashes in my analytics, but I can't track them down, so this method is probably not a good solution.

**Comment by whoyawn** [comment]
Any updates on this? Is this still an issue?

**Comment by Kaspik** [comment]
Should be fixed in 4.0.0.
